// AUTO-GENERATED from /site-assets/portfolio. Every media path below exists in /public/portfolio.
export type ProjectImage = { src: string; w: number; h: number }
export type ProjectVideo = { src: string; poster?: string; w: number; h: number; duration?: string }

export type Project = {
  slug: string
  title: string
  category: Exclude<Category, "All">
  client: string
  year: string
  description: string
  role: string
  featured: boolean
  images: ProjectImage[]
  videos: ProjectVideo[]
}

export const projects: Project[] = [
  {
    slug: "orevce-cheese-packaging-design",
    title: "Orevce Cheese Packaging Design",
    category: "Packaging",
    client: "Orevce",
    year: "2026",
    role: "Packaging Designer / Brand Visual Designer",
    description: "Premium packaging direction for Orevce, focused on product presence, shelf impact and a clean brand presentation. The project combines packaging design, visual hierarchy and product-focused storytelling to create a more professional and recognizable cheese brand experience.",
    featured: true,
    images: [
      { src: "/portfolio/orevce-cheese-packaging-design/orevce-cheese-packaging-design-01.webp", w: 1920, h: 1080 },
      { src: "/portfolio/orevce-cheese-packaging-design/orevce-cheese-packaging-design-02.webp", w: 1920, h: 1080 },
      { src: "/portfolio/orevce-cheese-packaging-design/orevce-cheese-packaging-design-03.webp", w: 1920, h: 1080 },
      { src: "/portfolio/orevce-cheese-packaging-design/orevce-cheese-packaging-design-04.webp", w: 1920, h: 1080 },
      { src: "/portfolio/orevce-cheese-packaging-design/orevce-cheese-packaging-design-05.webp", w: 1920, h: 1080 },
      { src: "/portfolio/orevce-cheese-packaging-design/orevce-cheese-packaging-design-06.webp", w: 1920, h: 1080 },
      { src: "/portfolio/orevce-cheese-packaging-design/orevce-cheese-packaging-design-07.webp", w: 1920, h: 1080 },
      { src: "/portfolio/orevce-cheese-packaging-design/orevce-cheese-packaging-design-08.webp", w: 1920, h: 1080 },
      { src: "/portfolio/orevce-cheese-packaging-design/orevce-cheese-packaging-design-09.webp", w: 1920, h: 1080 },
      { src: "/portfolio/orevce-cheese-packaging-design/orevce-cheese-packaging-design-10.webp", w: 1920, h: 1080 },
      { src: "/portfolio/orevce-cheese-packaging-design/orevce-cheese-packaging-design-11.webp", w: 1920, h: 1080 },
      { src: "/portfolio/orevce-cheese-packaging-design/orevce-cheese-packaging-design-12.webp", w: 1920, h: 1080 },
    ],
    videos: [
    ],
  },
  {
    slug: "sexopoly-packaging-design",
    title: "Sexopoly Packaging Design",
    category: "Packaging",
    client: "Sexopoly",
    year: "2026",
    role: "Packaging Designer / Visual Designer",
    description: "Bold packaging and product presentation system with a clear hierarchy, playful visual direction and a polished retail-ready finish.",
    featured: false,
    images: [
      { src: "/portfolio/sexopoly-packaging-design/sexopoly-packaging-design-01.webp", w: 1920, h: 1080 },
      { src: "/portfolio/sexopoly-packaging-design/sexopoly-packaging-design-02.webp", w: 1920, h: 1080 },
      { src: "/portfolio/sexopoly-packaging-design/sexopoly-packaging-design-03.webp", w: 811, h: 205 },
      { src: "/portfolio/sexopoly-packaging-design/sexopoly-packaging-design-04.webp", w: 1265, h: 813 },
      { src: "/portfolio/sexopoly-packaging-design/sexopoly-packaging-design-05.webp", w: 1264, h: 632 },
      { src: "/portfolio/sexopoly-packaging-design/sexopoly-packaging-design-06.webp", w: 1264, h: 625 },
      { src: "/portfolio/sexopoly-packaging-design/sexopoly-packaging-design-07.webp", w: 1263, h: 630 },
      { src: "/portfolio/sexopoly-packaging-design/sexopoly-packaging-design-08.webp", w: 1263, h: 628 },
      { src: "/portfolio/sexopoly-packaging-design/sexopoly-packaging-design-09.webp", w: 1264, h: 631 },
      { src: "/portfolio/sexopoly-packaging-design/sexopoly-packaging-design-10.webp", w: 1264, h: 815 },
      { src: "/portfolio/sexopoly-packaging-design/sexopoly-packaging-design-11.webp", w: 1139, h: 1139 },
      { src: "/portfolio/sexopoly-packaging-design/sexopoly-packaging-design-12.webp", w: 1202, h: 1202 },
    ],
    videos: [
    ],
  },
  {
    slug: "battery-evolution-social-media",
    title: "Battery Evolution Social Media",
    category: "Social Media",
    client: "Battery Evolution",
    year: "2026",
    role: "Creative Lead & Marketing Strategist",
    description: "B2B-focused social media visuals for the battery and energy market, built around product communication, importer and distributor messaging, and consistent brand presence.",
    featured: false,
    images: [
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-01.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-03.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-04.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-05.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-06.webp", w: 1082, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-07.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-08.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-09.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-10.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-11.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-12.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-13.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-14.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-15.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-16.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-17.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-18.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-19.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-20.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-21.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-22.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-23.webp", w: 1080, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-24.webp", w: 1077, h: 1350 },
      { src: "/portfolio/battery-evolution-social-media/battery-evolution-social-media-25.webp", w: 1369, h: 1149 },
    ],
    videos: [
    ],
  },
  {
    slug: "exide-social-media",
    title: "EXIDE Social Media",
    category: "Social Media",
    client: "EXIDE",
    year: "2026",
    role: "Creative Lead & Marketing Strategist",
    description: "Sales-focused social media visuals for automotive battery products, designed to communicate model benefits, offers and brand trust with a clean retail presentation.",
    featured: false,
    images: [
      { src: "/portfolio/exide-social-media/exide-social-media-01.webp", w: 1080, h: 1350 },
      { src: "/portfolio/exide-social-media/exide-social-media-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/exide-social-media/exide-social-media-03.webp", w: 1206, h: 1507 },
      { src: "/portfolio/exide-social-media/exide-social-media-04.webp", w: 972, h: 1215 },
      { src: "/portfolio/exide-social-media/exide-social-media-05.webp", w: 1080, h: 1350 },
      { src: "/portfolio/exide-social-media/exide-social-media-06.webp", w: 1080, h: 1350 },
      { src: "/portfolio/exide-social-media/exide-social-media-07.webp", w: 512, h: 640 },
      { src: "/portfolio/exide-social-media/exide-social-media-08.webp", w: 512, h: 640 },
      { src: "/portfolio/exide-social-media/exide-social-media-09.webp", w: 1080, h: 1350 },
      { src: "/portfolio/exide-social-media/exide-social-media-10.webp", w: 1080, h: 1350 },
      { src: "/portfolio/exide-social-media/exide-social-media-11.webp", w: 1080, h: 1350 },
      { src: "/portfolio/exide-social-media/exide-social-media-12.webp", w: 1080, h: 1350 },
      { src: "/portfolio/exide-social-media/exide-social-media-13.webp", w: 1080, h: 1350 },
      { src: "/portfolio/exide-social-media/exide-social-media-14.webp", w: 1080, h: 1350 },
      { src: "/portfolio/exide-social-media/exide-social-media-15.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "akumulatorimk-social-media",
    title: "Akumulatori.mk Social Media",
    category: "Social Media",
    client: "Akumulatori.mk",
    year: "2026",
    role: "Creative Lead & Marketing Strategist",
    description: "Retail content system for automotive batteries, combining product offers, educational posts and seasonal campaign visuals for stronger digital sales communication.",
    featured: false,
    images: [
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-01.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-03.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-04.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-05.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-06.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-07.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-08.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-09.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-10.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-11.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-12.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-13.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-14.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-15.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-16.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-17.webp", w: 1080, h: 1350 },
      { src: "/portfolio/akumulatorimk-social-media/akumulatorimk-social-media-18.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "solar-energy-mk",
    title: "Solar Energy MK Campaign Visuals",
    category: "Campaigns",
    client: "Solar Energy MK",
    year: "2026",
    role: "Creative Lead & Marketing Strategist",
    description: "Clean energy campaign visuals focused on solar products, battery systems, platform communication and professional B2B presentation.",
    featured: false,
    images: [
      { src: "/portfolio/solar-energy-mk/solar-energy-mk-01.webp", w: 1080, h: 1350 },
      { src: "/portfolio/solar-energy-mk/solar-energy-mk-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/solar-energy-mk/solar-energy-mk-03.webp", w: 1080, h: 1350 },
      { src: "/portfolio/solar-energy-mk/solar-energy-mk-04.webp", w: 1080, h: 1350 },
      { src: "/portfolio/solar-energy-mk/solar-energy-mk-05.webp", w: 1080, h: 1350 },
      { src: "/portfolio/solar-energy-mk/solar-energy-mk-06.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "mono-alex-social-media",
    title: "Mono Alex Social Media",
    category: "Social Media",
    client: "Mono Alex Clothing Brand",
    year: "2025–2026",
    role: "Senior Designer & Creative Lead",
    description: "Creative direction for a clothing brand, covering social media visuals, product presentation, campaign graphics, website visuals and AI-assisted fashion content workflows.",
    featured: false,
    images: [
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-01.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-03.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-04.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-05.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-06.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-07.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-08.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-09.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-10.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-11.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-12.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-13.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-14.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-15.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-16.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-17.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-18.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-19.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-20.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-21.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-22.webp", w: 1080, h: 1350 },
      { src: "/portfolio/mono-alex-social-media/mono-alex-social-media-23.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "merkur-social-media",
    title: "Merkur Social Media",
    category: "Social Media",
    client: "Merkur",
    year: "2025",
    role: "Graphic Designer",
    description: "Retail social media visuals and promotional content built around product offers, seasonal communication and clear shopping-driven messages.",
    featured: false,
    images: [
      { src: "/portfolio/merkur-social-media/merkur-social-media-01.webp", w: 716, h: 897 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-02.webp", w: 897, h: 896 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-03.webp", w: 898, h: 897 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-04.webp", w: 897, h: 894 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-05.webp", w: 717, h: 896 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-06.webp", w: 1080, h: 1350 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-07.webp", w: 1080, h: 1350 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-08.webp", w: 1080, h: 1080 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-09.webp", w: 1080, h: 1080 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-10.webp", w: 1080, h: 1350 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-11.webp", w: 1080, h: 1080 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-12.webp", w: 1080, h: 1080 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-13.webp", w: 1080, h: 1350 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-14.webp", w: 1080, h: 1350 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-15.webp", w: 1080, h: 1350 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-16.webp", w: 1080, h: 1080 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-17.webp", w: 1080, h: 1350 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-18.webp", w: 1080, h: 1350 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-19.webp", w: 1080, h: 1080 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-20.webp", w: 1080, h: 1080 },
      { src: "/portfolio/merkur-social-media/merkur-social-media-21.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "mowo-social-media",
    title: "Mowo Social Media",
    category: "Social Media",
    client: "Mowo",
    year: "2025",
    role: "Graphic Designer",
    description: "Modern social media visual direction with clean layouts, consistent post systems and brand-focused digital communication.",
    featured: false,
    images: [
      { src: "/portfolio/mowo-social-media/mowo-social-media-01.webp", w: 717, h: 896 },
      { src: "/portfolio/mowo-social-media/mowo-social-media-02.webp", w: 714, h: 897 },
      { src: "/portfolio/mowo-social-media/mowo-social-media-03.webp", w: 713, h: 895 },
      { src: "/portfolio/mowo-social-media/mowo-social-media-04.webp", w: 716, h: 897 },
      { src: "/portfolio/mowo-social-media/mowo-social-media-05.webp", w: 717, h: 895 },
      { src: "/portfolio/mowo-social-media/mowo-social-media-06.webp", w: 716, h: 895 },
      { src: "/portfolio/mowo-social-media/mowo-social-media-07.webp", w: 715, h: 893 },
      { src: "/portfolio/mowo-social-media/mowo-social-media-08.webp", w: 714, h: 894 },
      { src: "/portfolio/mowo-social-media/mowo-social-media-09.webp", w: 713, h: 893 },
      { src: "/portfolio/mowo-social-media/mowo-social-media-10.webp", w: 714, h: 895 },
      { src: "/portfolio/mowo-social-media/mowo-social-media-11.webp", w: 716, h: 895 },
      { src: "/portfolio/mowo-social-media/mowo-social-media-12.webp", w: 717, h: 892 },
      { src: "/portfolio/mowo-social-media/mowo-social-media-13.webp", w: 717, h: 895 },
      { src: "/portfolio/mowo-social-media/mowo-social-media-14.webp", w: 715, h: 896 },
      { src: "/portfolio/mowo-social-media/mowo-social-media-15.webp", w: 714, h: 895 },
      { src: "/portfolio/mowo-social-media/mowo-social-media-16.webp", w: 768, h: 960 },
    ],
    videos: [
    ],
  },
  {
    slug: "tehnotrans-social-media",
    title: "Tehnotrans Social Media",
    category: "Social Media",
    client: "Tehnotrans",
    year: "2023–2024",
    role: "Full Service Creative",
    description: "Transport and logistics social media visuals designed to communicate service reliability, fleet presence and professional company communication.",
    featured: false,
    images: [
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-01.webp", w: 1255, h: 1251 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-02.webp", w: 1252, h: 1253 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-03.webp", w: 1258, h: 1250 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-04.webp", w: 1256, h: 1257 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-05.webp", w: 1257, h: 1251 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-06.webp", w: 1248, h: 1256 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-07.webp", w: 1257, h: 1250 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-08.webp", w: 1257, h: 1258 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-09.webp", w: 1257, h: 1255 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-10.webp", w: 1257, h: 1255 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-11.webp", w: 1258, h: 1257 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-12.webp", w: 1257, h: 1254 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-13.webp", w: 1255, h: 1258 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-14.webp", w: 1252, h: 1253 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-15.webp", w: 1255, h: 1256 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-16.webp", w: 1255, h: 1256 },
      { src: "/portfolio/tehnotrans-social-media/tehnotrans-social-media-17.webp", w: 1255, h: 1256 },
    ],
    videos: [
    ],
  },
  {
    slug: "d-sped-transport-social-media",
    title: "D-Sped Transport Social Media",
    category: "Social Media",
    client: "D-Sped Transport",
    year: "2024–2025",
    role: "Graphic Designer",
    description: "Social media system for a transport company, including recruitment communication, fleet presentation and B2B trust-building visuals.",
    featured: false,
    images: [
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-01.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-03.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-04.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-05.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-06.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-07.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-08.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-09.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-10.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-11.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-12.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-13.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-14.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-15.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-16.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-17.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-18.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-19.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-20.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-21.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-22.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-23.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-24.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-25.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-26.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-27.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-28.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-29.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-30.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-31.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-32.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-33.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-34.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-35.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-36.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-37.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-38.webp", w: 1080, h: 1350 },
      { src: "/portfolio/d-sped-transport-social-media/d-sped-transport-social-media-39.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "prodavnica-za-gumi-social-media",
    title: "Tire Shop Social Media",
    category: "Social Media",
    client: "Prodavnica za Gumi",
    year: "2025",
    role: "Graphic Designer",
    description: "Seasonal, offer-driven visuals for tire retail, focused on clear product presentation, automotive context and sales-oriented layouts.",
    featured: false,
    images: [
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-01.webp", w: 1080, h: 1350 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-03.webp", w: 1080, h: 1350 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-04.webp", w: 1080, h: 1350 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-05.webp", w: 1080, h: 1350 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-06.webp", w: 1080, h: 1350 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-07.webp", w: 1080, h: 1350 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-08.webp", w: 1080, h: 1350 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-09.webp", w: 1080, h: 1350 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-10.webp", w: 1080, h: 1350 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-11.webp", w: 1080, h: 1350 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-12.webp", w: 640, h: 800 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-13.webp", w: 640, h: 800 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-14.webp", w: 640, h: 800 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-15.webp", w: 640, h: 800 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-16.webp", w: 640, h: 800 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-17.webp", w: 640, h: 800 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-18.webp", w: 640, h: 800 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-19.webp", w: 640, h: 800 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-20.webp", w: 640, h: 800 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-21.webp", w: 640, h: 800 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-22.webp", w: 640, h: 800 },
      { src: "/portfolio/prodavnica-za-gumi-social-media/prodavnica-za-gumi-social-media-23.webp", w: 640, h: 800 },
    ],
    videos: [
    ],
  },
  {
    slug: "service-milosheski-social-media",
    title: "Service Milosheski Social Media",
    category: "Social Media",
    client: "Service Milosheski",
    year: "2025",
    role: "Graphic Designer",
    description: "Automotive service visuals built for trust, clarity and consistent communication across social media formats.",
    featured: false,
    images: [
      { src: "/portfolio/service-milosheski-social-media/service-milosheski-social-media-01.webp", w: 1080, h: 1350 },
      { src: "/portfolio/service-milosheski-social-media/service-milosheski-social-media-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/service-milosheski-social-media/service-milosheski-social-media-03.webp", w: 1080, h: 1350 },
      { src: "/portfolio/service-milosheski-social-media/service-milosheski-social-media-04.webp", w: 640, h: 800 },
      { src: "/portfolio/service-milosheski-social-media/service-milosheski-social-media-05.webp", w: 640, h: 800 },
      { src: "/portfolio/service-milosheski-social-media/service-milosheski-social-media-06.webp", w: 640, h: 800 },
      { src: "/portfolio/service-milosheski-social-media/service-milosheski-social-media-07.webp", w: 640, h: 800 },
      { src: "/portfolio/service-milosheski-social-media/service-milosheski-social-media-08.webp", w: 640, h: 800 },
      { src: "/portfolio/service-milosheski-social-media/service-milosheski-social-media-09.webp", w: 640, h: 800 },
      { src: "/portfolio/service-milosheski-social-media/service-milosheski-social-media-10.webp", w: 640, h: 800 },
      { src: "/portfolio/service-milosheski-social-media/service-milosheski-social-media-11.webp", w: 640, h: 797 },
      { src: "/portfolio/service-milosheski-social-media/service-milosheski-social-media-12.webp", w: 640, h: 800 },
      { src: "/portfolio/service-milosheski-social-media/service-milosheski-social-media-13.webp", w: 640, h: 798 },
      { src: "/portfolio/service-milosheski-social-media/service-milosheski-social-media-14.webp", w: 1080, h: 1350 },
      { src: "/portfolio/service-milosheski-social-media/service-milosheski-social-media-15.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "lorens-cafe-bar-social-media",
    title: "Lorens Cafe Bar Social Media",
    category: "Social Media",
    client: "Lorens Cafe Bar",
    year: "2025",
    role: "Graphic Designer",
    description: "Hospitality social media visuals for drinks, offers, events and atmosphere-driven communication with a strong promotional focus.",
    featured: false,
    images: [
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-01.webp", w: 1080, h: 1350 },
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-03.webp", w: 1080, h: 1350 },
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-04.webp", w: 768, h: 960 },
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-05.webp", w: 768, h: 960 },
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-06.webp", w: 768, h: 960 },
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-07.webp", w: 1080, h: 1350 },
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-08.webp", w: 1080, h: 1350 },
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-09.webp", w: 736, h: 920 },
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-10.webp", w: 1080, h: 1350 },
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-11.webp", w: 1080, h: 1350 },
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-12.webp", w: 1080, h: 1350 },
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-13.webp", w: 1080, h: 1350 },
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-14.webp", w: 1080, h: 1350 },
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-15.webp", w: 1080, h: 1350 },
      { src: "/portfolio/lorens-cafe-bar-social-media/lorens-cafe-bar-social-media-16.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "magic-events-organizatori-na-nokjni-zabavi-social-media",
    title: "Magic Events Social Media",
    category: "Social Media",
    client: "Magic Events",
    year: "2025",
    role: "Graphic Designer",
    description: "Nightlife and event visuals created for energetic announcements, party promotion and clear event communication.",
    featured: false,
    images: [
      { src: "/portfolio/magic-events-organizatori-na-nokjni-zabavi-social-media/magic-events-organizatori-na-nokjni-zabavi-social-media-01.webp", w: 640, h: 800 },
      { src: "/portfolio/magic-events-organizatori-na-nokjni-zabavi-social-media/magic-events-organizatori-na-nokjni-zabavi-social-media-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/magic-events-organizatori-na-nokjni-zabavi-social-media/magic-events-organizatori-na-nokjni-zabavi-social-media-03.webp", w: 1080, h: 1350 },
      { src: "/portfolio/magic-events-organizatori-na-nokjni-zabavi-social-media/magic-events-organizatori-na-nokjni-zabavi-social-media-04.webp", w: 1080, h: 1350 },
      { src: "/portfolio/magic-events-organizatori-na-nokjni-zabavi-social-media/magic-events-organizatori-na-nokjni-zabavi-social-media-05.webp", w: 1080, h: 1350 },
      { src: "/portfolio/magic-events-organizatori-na-nokjni-zabavi-social-media/magic-events-organizatori-na-nokjni-zabavi-social-media-06.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "dj-dorijan-social-media",
    title: "DJ Dorijan Social Media",
    category: "Social Media",
    client: "DJ Dorijan",
    year: "2025",
    role: "Graphic Designer",
    description: "Music and nightlife visuals designed for artist promotion, events and high-impact social media presence.",
    featured: false,
    images: [
      { src: "/portfolio/dj-dorijan-social-media/dj-dorijan-social-media-01.webp", w: 1080, h: 1350 },
      { src: "/portfolio/dj-dorijan-social-media/dj-dorijan-social-media-02.webp", w: 1080, h: 1920 },
      { src: "/portfolio/dj-dorijan-social-media/dj-dorijan-social-media-03.webp", w: 1080, h: 1350 },
      { src: "/portfolio/dj-dorijan-social-media/dj-dorijan-social-media-04.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "san-marti-social-media",
    title: "San Marti Social Media",
    category: "Social Media",
    client: "San Marti",
    year: "2025",
    role: "Graphic Designer",
    description: "Product-led social media visuals for home and bathroom brands, balancing premium product presentation with clear offer communication.",
    featured: false,
    images: [
      { src: "/portfolio/san-marti-social-media/san-marti-social-media-01.webp", w: 1080, h: 1350 },
      { src: "/portfolio/san-marti-social-media/san-marti-social-media-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/san-marti-social-media/san-marti-social-media-03.webp", w: 1080, h: 1350 },
      { src: "/portfolio/san-marti-social-media/san-marti-social-media-04.webp", w: 1080, h: 1350 },
      { src: "/portfolio/san-marti-social-media/san-marti-social-media-05.webp", w: 1080, h: 1350 },
      { src: "/portfolio/san-marti-social-media/san-marti-social-media-06.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "marija-spasovska-singer",
    title: "Marija Spasovska Singer Campaign",
    category: "Campaigns",
    client: "Marija Spasovska",
    year: "2025",
    role: "Graphic Designer",
    description: "Music artist campaign visuals created for a polished public-facing presentation across digital formats.",
    featured: false,
    images: [
      { src: "/portfolio/marija-spasovska-singer/marija-spasovska-singer-01.webp", w: 1080, h: 1350 },
      { src: "/portfolio/marija-spasovska-singer/marija-spasovska-singer-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/marija-spasovska-singer/marija-spasovska-singer-03.webp", w: 1600, h: 1600 },
      { src: "/portfolio/marija-spasovska-singer/marija-spasovska-singer-04.webp", w: 1080, h: 1920 },
      { src: "/portfolio/marija-spasovska-singer/marija-spasovska-singer-05.webp", w: 1080, h: 1920 },
    ],
    videos: [
    ],
  },
  {
    slug: "vasil-angelov-singer",
    title: "Vasil Angelov Singer Campaign",
    category: "Campaigns",
    client: "Vasil Angelov",
    year: "2025",
    role: "Graphic Designer",
    description: "Artist-focused visuals with a promotional direction for music releases, social media and public communication.",
    featured: false,
    images: [
      { src: "/portfolio/vasil-angelov-singer/vasil-angelov-singer-01.webp", w: 1080, h: 1920 },
      { src: "/portfolio/vasil-angelov-singer/vasil-angelov-singer-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/vasil-angelov-singer/vasil-angelov-singer-03.webp", w: 1080, h: 1920 },
      { src: "/portfolio/vasil-angelov-singer/vasil-angelov-singer-04.webp", w: 1080, h: 1350 },
      { src: "/portfolio/vasil-angelov-singer/vasil-angelov-singer-05.webp", w: 1080, h: 1920 },
      { src: "/portfolio/vasil-angelov-singer/vasil-angelov-singer-06.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "los-blancos-balkan",
    title: "Los Blancos Balkan",
    category: "Sports",
    client: "Football Media",
    year: "2025–2026",
    role: "Sports Visual Designer",
    description: "Football media visuals for Real Madrid-focused content, combining sports storytelling, transfer-style graphics and fan community communication.",
    featured: false,
    images: [
      { src: "/portfolio/los-blancos-balkan/los-blancos-balkan-01.webp", w: 1080, h: 1350 },
      { src: "/portfolio/los-blancos-balkan/los-blancos-balkan-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/los-blancos-balkan/los-blancos-balkan-03.webp", w: 1080, h: 1350 },
      { src: "/portfolio/los-blancos-balkan/los-blancos-balkan-04.webp", w: 1080, h: 1350 },
      { src: "/portfolio/los-blancos-balkan/los-blancos-balkan-05.webp", w: 1080, h: 1350 },
      { src: "/portfolio/los-blancos-balkan/los-blancos-balkan-06.webp", w: 1080, h: 1350 },
      { src: "/portfolio/los-blancos-balkan/los-blancos-balkan-07.webp", w: 1080, h: 1350 },
      { src: "/portfolio/los-blancos-balkan/los-blancos-balkan-08.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "cisto-skopje-social-media",
    title: "Čisto Skopje Campaign",
    category: "Campaigns",
    client: "Čisto Skopje",
    year: "2026",
    role: "Campaign Visual Designer",
    description: "Public awareness campaign visuals with a clean, direct communication style and campaign-ready social media formats.",
    featured: false,
    images: [
      { src: "/portfolio/cisto-skopje-social-media/cisto-skopje-social-media-01.webp", w: 1080, h: 1350 },
      { src: "/portfolio/cisto-skopje-social-media/cisto-skopje-social-media-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/cisto-skopje-social-media/cisto-skopje-social-media-03.webp", w: 1080, h: 1350 },
      { src: "/portfolio/cisto-skopje-social-media/cisto-skopje-social-media-04.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "court-kingz-custom-poster",
    title: "Court Kingz Custom Poster",
    category: "Sports",
    client: "Court Kingz",
    year: "2025",
    role: "Poster Designer",
    description: "High-impact basketball poster design with an energetic sports look, strong composition and custom visual treatment.",
    featured: false,
    images: [
      { src: "/portfolio/court-kingz-custom-poster/court-kingz-custom-poster-01.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "custom-concept-posters",
    title: "Custom Concept Posters",
    category: "Posters",
    client: "Concept Work",
    year: "2025",
    role: "Poster Designer",
    description: "A collection of custom poster concepts focused on visual impact, composition, mood and strong editorial presentation.",
    featured: false,
    images: [
      { src: "/portfolio/custom-concept-posters/custom-concept-posters-01.webp", w: 640, h: 800 },
      { src: "/portfolio/custom-concept-posters/custom-concept-posters-02.webp", w: 640, h: 800 },
      { src: "/portfolio/custom-concept-posters/custom-concept-posters-03.webp", w: 640, h: 800 },
      { src: "/portfolio/custom-concept-posters/custom-concept-posters-04.webp", w: 640, h: 800 },
    ],
    videos: [
    ],
  },
  {
    slug: "igor-stefanovski-idze-posters",
    title: "Igor Stefanovski IDŽE Posters",
    category: "Sports",
    client: "Igor Stefanovski IDŽE",
    year: "2025",
    role: "Poster Designer",
    description: "Motorsport poster visuals built around speed, power and race-day energy for a championship hillclimb driver.",
    featured: false,
    images: [
      { src: "/portfolio/igor-stefanovski-idze-posters/igor-stefanovski-idze-posters-01.webp", w: 640, h: 800 },
      { src: "/portfolio/igor-stefanovski-idze-posters/igor-stefanovski-idze-posters-02.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "jts-logistics-poster",
    title: "JTS Logistics Poster",
    category: "Posters",
    client: "JTS Logistics",
    year: "2025",
    role: "Poster Designer",
    description: "Promotional logistics poster design with clear hierarchy, service communication and a professional B2B visual tone.",
    featured: false,
    images: [
      { src: "/portfolio/jts-logistics-poster/jts-logistics-poster-01.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
  {
    slug: "teatar-hit-skopje-poster",
    title: "Teatar HIT Skopje Poster",
    category: "Posters",
    client: "Teatar HIT Skopje",
    year: "2025",
    role: "Poster Designer",
    description: "Theatre poster design focused on dramatic presentation, readable hierarchy and event-ready visual communication.",
    featured: false,
    images: [
      { src: "/portfolio/teatar-hit-skopje-poster/teatar-hit-skopje-poster-01.webp", w: 972, h: 1215 },
    ],
    videos: [
    ],
  },
  {
    slug: "moto-kapitol-logo-design",
    title: "Moto Kapitol Logo Design",
    category: "Logos",
    client: "Moto Kapitol",
    year: "2026",
    role: "Logo Designer / Brand Designer",
    description: "Logo and identity direction for a motorcycle-related brand, designed to feel bold, recognizable and production-ready across applications.",
    featured: false,
    images: [
      { src: "/portfolio/moto-kapitol-logo-design/moto-kapitol-logo-design-01.webp", w: 1920, h: 1080 },
      { src: "/portfolio/moto-kapitol-logo-design/moto-kapitol-logo-design-02.webp", w: 1920, h: 1080 },
      { src: "/portfolio/moto-kapitol-logo-design/moto-kapitol-logo-design-03.webp", w: 1920, h: 1080 },
      { src: "/portfolio/moto-kapitol-logo-design/moto-kapitol-logo-design-04.webp", w: 1920, h: 1080 },
    ],
    videos: [
    ],
  },
  {
    slug: "sky-city-deluxe-logo-design",
    title: "Sky City Deluxe Logo Design",
    category: "Logos",
    client: "Sky City Deluxe",
    year: "2026",
    role: "Logo Designer / Brand Designer",
    description: "Premium logo design direction for a residential/apartment brand, with a clean identity system suited for property and hospitality communication.",
    featured: false,
    images: [
      { src: "/portfolio/sky-city-deluxe-logo-design/sky-city-deluxe-logo-design-01.webp", w: 1920, h: 1080 },
      { src: "/portfolio/sky-city-deluxe-logo-design/sky-city-deluxe-logo-design-02.webp", w: 1920, h: 1080 },
      { src: "/portfolio/sky-city-deluxe-logo-design/sky-city-deluxe-logo-design-03.webp", w: 1920, h: 1080 },
      { src: "/portfolio/sky-city-deluxe-logo-design/sky-city-deluxe-logo-design-04.webp", w: 1920, h: 1080 },
    ],
    videos: [
    ],
  },
  {
    slug: "ac-milan-logo-concept",
    title: "AC Milan Logo Concept",
    category: "Sports",
    client: "Concept Work",
    year: "2025",
    role: "Logo Concept Designer",
    description: "Sports logo concept exploration inspired by football identity, heritage and modern badge design systems.",
    featured: false,
    images: [
      { src: "/portfolio/ac-milan-logo-concept/ac-milan-logo-concept-01.webp", w: 2051, h: 1026 },
      { src: "/portfolio/ac-milan-logo-concept/ac-milan-logo-concept-02.webp", w: 2559, h: 1279 },
      { src: "/portfolio/ac-milan-logo-concept/ac-milan-logo-concept-03.webp", w: 2559, h: 1280 },
      { src: "/portfolio/ac-milan-logo-concept/ac-milan-logo-concept-04.webp", w: 2559, h: 1279 },
      { src: "/portfolio/ac-milan-logo-concept/ac-milan-logo-concept-05.webp", w: 2559, h: 1279 },
      { src: "/portfolio/ac-milan-logo-concept/ac-milan-logo-concept-06.webp", w: 2559, h: 1277 },
      { src: "/portfolio/ac-milan-logo-concept/ac-milan-logo-concept-07.webp", w: 1918, h: 1085 },
    ],
    videos: [
    ],
  },
  {
    slug: "newcastle-logo-concept-redesign",
    title: "Newcastle Logo Concept Redesign",
    category: "Sports",
    client: "Concept Work",
    year: "2025",
    role: "Logo Concept Designer",
    description: "Football crest redesign concept focused on simplifying heritage elements into a cleaner modern sports identity.",
    featured: false,
    images: [
      { src: "/portfolio/newcastle-logo-concept-redesign/newcastle-logo-concept-redesign-01.webp", w: 1920, h: 1080 },
      { src: "/portfolio/newcastle-logo-concept-redesign/newcastle-logo-concept-redesign-02.webp", w: 1920, h: 1080 },
      { src: "/portfolio/newcastle-logo-concept-redesign/newcastle-logo-concept-redesign-03.webp", w: 1920, h: 1080 },
      { src: "/portfolio/newcastle-logo-concept-redesign/newcastle-logo-concept-redesign-04.webp", w: 1920, h: 1080 },
      { src: "/portfolio/newcastle-logo-concept-redesign/newcastle-logo-concept-redesign-05.webp", w: 1920, h: 1080 },
    ],
    videos: [
    ],
  },
  {
    slug: "tedy-max-trans-social-media",
    title: "Tedy Max Trans Social Media",
    category: "Social Media",
    client: "Tedy Max Trans",
    year: "2025",
    role: "Graphic Designer",
    description: "Transport company social media visuals designed for professional service communication, recruitment and brand consistency.",
    featured: false,
    images: [
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-01.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-02.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-03.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-04.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-05.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-06.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-07.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-08.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-09.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-10.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-11.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-12.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-13.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-14.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-15.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-16.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-17.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-18.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-19.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-20.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-21.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-22.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-23.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-24.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-25.webp", w: 1080, h: 1350 },
      { src: "/portfolio/tedy-max-trans-social-media/tedy-max-trans-social-media-26.webp", w: 1080, h: 1350 },
    ],
    videos: [
    ],
  },
]

export const categories = ["All", "Packaging", "Social Media", "Campaigns", "Logos", "Posters", "Sports"] as const
export type Category = (typeof categories)[number]

export function cover(p: Project): string {
  return p.videos[0]?.poster ?? p.images[0]?.src ?? ""
}

export function mediaCount(p: Project): number {
  return p.images.length + p.videos.length
}
